---
title: Judit Fischer
timezone: UTC
exclude:
- README.md

url: juditfischer.com
permalink: pretty
livereload: true     # You no longer need to include --livereload
incremental: true

collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:name"
  uploads:
    title: Uploads
    output: true

defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: default
    title: "--Title--"
    gallery:
    - image: http://placekitten.com/200/300
      caption: ''

